<?php

namespace Test\CrudBundle\Repository\Entity;

/**
 * BallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BallesRepository extends \Doctrine\ORM\EntityRepository
{
}
