<?php

namespace Test\CrudBundle\Repository\Entity;

/**
 * FichiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersRepository extends \Doctrine\ORM\EntityRepository
{
}
