<?php

namespace Test\CrudBundle\Repository\Entity;

/**
 * MembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresRepository extends \Doctrine\ORM\EntityRepository
{
}
