<?php

namespace MS\MembresBundle\Repository;

/**
 * MSMembresBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MSMembresBundleRepository extends \Doctrine\ORM\EntityRepository
{
}
