<?php

namespace Test\CrudBundle\Repository\Entity;

/**
 * ConversationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationsRepository extends \Doctrine\ORM\EntityRepository
{
}
